### ISSUE TITLE
PhantomJS not installed

### ISSUE THREAD

**Issue by patrickisgreat** [cburgdorf/grunt-html-snapshot#13]
Hi -- I'm testing out this awesome node package on a CentOS 6.5 box

I've got grunt installed and have initialized a project. I've successfully installed the package and checked to be sure that the package.json is configured correctly. I've got the task configured in Gruntfile.js with my parameters.

When I run grunt htmlSnapshot -- I get the following error: 

Running PhantomJS...ERROR

> > In order for this task to work properly, PhantomJS must be installed locally
> > via NPM. If you're seeing this message, generally that means the NPM install
> > has failed. Please submit an issue providing as much detail as possible at:
> > https://github.com/gruntjs/grunt-lib-phantomjs/issues
> > Warning: PhantomJS not found. Use --force to continue.

Aborted due to warnings.

I have checked to make sure phantomjs is installed and I've even reinstalled it using npm install phantomjs then node install.js

Is this just a path issue ? 

Do I need to create a sym link?  If so from where to where ?

**Comment by CrackerakiUA** [comment]
I have familiar issue, and i have installed everything correctly, and phantomjs looks to work. Any idea?
